name: Build to release branches

on:
    workflow_dispatch:
    push:
        tags: ['*']
        branches:
            - dev-beta
            - dev-main

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: false

jobs:
    build-assets:
        uses: inpsyde/reusable-workflows/.github/workflows/build-and-push-assets.yml@add_option_to_select_built_branch_name
        with:
            PHP_VERSION: '8.1'
            PHP_TOOLS: composer:v2
            BUILT_BRANCH_NAME: "${{ (github.ref_name == 'dev-main' && 'main' || (github.ref_name == 'dev-beta' && 'beta') || '') }}"
            COMPILE_SCRIPT_PROD: 'build'
            COMPILE_SCRIPT_DEV: 'build:dev'
            MODE: "${{ github.ref_name == 'dev-beta' && 'dev' || 'prod'  }}"
        secrets:
            GITHUB_USER_EMAIL: ${{ secrets.DEPLOYBOT_EMAIL }}
            GITHUB_USER_NAME: ${{ secrets.DEPLOYBOT_USER }}
            GITHUB_USER_SSH_KEY: ${{ secrets.DEPLOYBOT_SSH_PRIVATE_KEY }}
            NPM_REGISTRY_TOKEN: ${{ secrets.DEPLOYBOT_PACKAGES_READ_ACCESS_TOKEN }}
