name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  release:
    uses: RRZE-Webteam/FAU-Studium-Common/.github/workflows/release.yml@main
    secrets:
      DEPLOYBOT_EMAIL: ${{ secrets.DEPLOYBOT_EMAIL }}
      DEPLOYBOT_USER: ${{ secrets.DEPLOYBOT_USER }}
