name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build-assets:
    uses: inpsyde/reusable-workflows/.github/workflows/build-and-push-assets.yml@main
    secrets:
      NPM_REGISTRY_TOKEN: ${{ secrets.DEPLOYBOT_PACKAGES_READ_ACCESS_TOKEN }}
      GITHUB_USER_EMAIL: ${{ secrets.DEPLOYBOT_EMAIL }}
      GITHUB_USER_NAME: ${{ secrets.DEPLOYBOT_USER }}
    with:
      PACKAGE_MANAGER: yarn

  build-release-archive:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [build-assets]
    env:
      PACKAGE_NAME: fau-studium

    steps:
      - name: Extract tag name into env
        run: echo "TAG_NAME=$(echo ${GITHUB_REF#refs/*/})" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.TAG_NAME }}

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2
        with:
          composer-options: "--no-dev"

      - name: Clean up
        run: rm -rf assets vendor

      - name: Git add, commit, push
        run: |
          git add .
          git commit -m "[BOT] Build package" --no-verify
          git push

      - name: Move tag
        run: |
          git tag -d ${{ env.TAG_NAME }}
          git push origin :refs/tags/${{ env.TAG_NAME }}
          git tag ${{ env.TAG_NAME }}
          git push origin --tags
